/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import javax.swing.JOptionPane;

/**
 *
 * @author Hyllmee
 */
public class MenuMakanan extends javax.swing.JFrame {

    /**
     * Creates new form MenuMakanan
     */
    public MenuMakanan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        head = new javax.swing.JLabel();
        Soto = new javax.swing.JRadioButton();
        Campur = new javax.swing.JRadioButton();
        Rawon = new javax.swing.JRadioButton();
        bebek = new javax.swing.JRadioButton();
        Lele = new javax.swing.JRadioButton();
        Ayam = new javax.swing.JRadioButton();
        Bihun = new javax.swing.JRadioButton();
        Padang = new javax.swing.JRadioButton();
        Lalapan = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        plus = new javax.swing.JButton();
        ok = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        jumlahtransaksi = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jumlah = new javax.swing.JLabel();
        minus = new javax.swing.JButton();
        hargasatuan = new javax.swing.JLabel();
        totalbayar = new javax.swing.JLabel();
        isipesanan = new javax.swing.JTextField();
        isihargasatuan = new javax.swing.JTextField();
        isitotalbayar = new javax.swing.JTextField();
        isijumlah = new javax.swing.JTextField();
        hargasatuan1 = new javax.swing.JLabel();
        btnKeluar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));

        head.setBackground(new java.awt.Color(255, 204, 0));
        head.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        head.setForeground(new java.awt.Color(51, 51, 51));
        head.setText("WAROENG YATOREH TOJUK");
        head.setMaximumSize(new java.awt.Dimension(396, 225));

        Soto.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        Soto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Soto.setForeground(new java.awt.Color(51, 51, 51));
        Soto.setText("Nasi Soto");
        Soto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SotoActionPerformed(evt);
            }
        });

        Campur.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        Campur.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Campur.setForeground(new java.awt.Color(51, 51, 51));
        Campur.setText("Nasi Campur");

        Rawon.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        Rawon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Rawon.setForeground(new java.awt.Color(51, 51, 51));
        Rawon.setText("Nasi Rawon");

        bebek.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        bebek.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bebek.setForeground(new java.awt.Color(51, 51, 51));
        bebek.setText("Bebek Goreng");

        Lele.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        Lele.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Lele.setForeground(new java.awt.Color(51, 51, 51));
        Lele.setText("Pecel Lele");

        Ayam.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        Ayam.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Ayam.setForeground(new java.awt.Color(51, 51, 51));
        Ayam.setText("Ayam Goreng");

        Bihun.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        Bihun.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Bihun.setForeground(new java.awt.Color(51, 51, 51));
        Bihun.setText("Bihun");

        Padang.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        Padang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Padang.setForeground(new java.awt.Color(51, 51, 51));
        Padang.setText("Nasi Padang");
        Padang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PadangActionPerformed(evt);
            }
        });

        Lalapan.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        Lalapan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Lalapan.setForeground(new java.awt.Color(51, 51, 51));
        Lalapan.setText("Lalapan Tempe Tahu");

        jPanel2.setBackground(new java.awt.Color(0, 0, 204));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setMaximumSize(new java.awt.Dimension(300, 350));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 400));

        jLabel1.setFont(new java.awt.Font("Sitka Subheading", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Transaksi");

        plus.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        plus.setForeground(new java.awt.Color(255, 255, 255));
        plus.setText("+");
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });

        ok.setText("Ok");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        jumlahtransaksi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jumlahtransaksi.setForeground(new java.awt.Color(255, 255, 255));
        jumlahtransaksi.setText("0");

        jLabel4.setFont(new java.awt.Font("Sitka Subheading", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Rincian Pesanan");

        jumlah.setForeground(new java.awt.Color(255, 255, 255));
        jumlah.setText("Jumlah         :");

        minus.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        minus.setForeground(new java.awt.Color(255, 255, 255));
        minus.setText("-");
        minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusActionPerformed(evt);
            }
        });

        hargasatuan.setForeground(new java.awt.Color(255, 255, 255));
        hargasatuan.setText("Harga/pcs   :");

        totalbayar.setForeground(new java.awt.Color(255, 255, 255));
        totalbayar.setText("Total Bayar  :");

        isipesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isipesananActionPerformed(evt);
            }
        });

        hargasatuan1.setForeground(new java.awt.Color(255, 255, 255));
        hargasatuan1.setText("Pesanan       :");

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(hargasatuan)
                            .addGap(17, 17, 17)
                            .addComponent(isihargasatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(minus, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jumlahtransaksi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(plus, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(ok)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(hapus)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(isijumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(totalbayar)
                                    .addGap(17, 17, 17)
                                    .addComponent(isitotalbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(hargasatuan1)
                        .addGap(18, 18, 18)
                        .addComponent(isipesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnKeluar)
                        .addGap(89, 89, 89))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jumlahtransaksi)
                    .addComponent(minus)
                    .addComponent(plus))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ok)
                    .addComponent(hapus))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isipesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hargasatuan1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hargasatuan)
                    .addComponent(isihargasatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jumlah)
                    .addComponent(isijumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalbayar)
                    .addComponent(isitotalbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKeluar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Campur)
                            .addComponent(Rawon)
                            .addComponent(Soto))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ayam)
                            .addComponent(bebek)
                            .addComponent(Lele))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lalapan)
                            .addComponent(Bihun)
                            .addComponent(Padang))
                        .addGap(34, 34, 34))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(head, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(head, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Soto)
                        .addGap(18, 18, 18)
                        .addComponent(Rawon)
                        .addGap(18, 18, 18)
                        .addComponent(Campur))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Padang)
                        .addGap(17, 17, 17)
                        .addComponent(Bihun)
                        .addGap(18, 18, 18)
                        .addComponent(Lalapan))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bebek)
                        .addGap(17, 17, 17)
                        .addComponent(Ayam)
                        .addGap(18, 18, 18)
                        .addComponent(Lele)))
                .addGap(82, 82, 82))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SotoActionPerformed

    private void PadangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PadangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PadangActionPerformed

    private void isipesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isipesananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isipesananActionPerformed

    private void minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusActionPerformed
        // TODO add your handling code here:
        int a = Integer.parseInt(jumlahtransaksi.getText());

        int b = a-1;
        jumlahtransaksi.setText(Integer.toString(b));
        if (a<=1){
            jumlahtransaksi.setText("1");
            JOptionPane.showMessageDialog(null, "Pesanan tidak dapat dilakukan", "ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_minusActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        isijumlah.setText("");
        isihargasatuan.setText("");
        isipesanan.setText("");
        jumlahtransaksi.setText("0");
        isitotalbayar.setText("");
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_hapusActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
        String menu = null;
        int harga = 0;
        int hitung = 0;
        int jumlah = Integer.parseInt(jumlahtransaksi.getText());

        if (Soto.isSelected()) {
            menu = "Nasi Soto";
            harga = 50000;
            hitung = jumlah * harga;
        }
        else if (Campur.isSelected()) {
            menu = "Nasi Campur";
            harga = 15000;
            hitung = jumlah * harga;
        }
        else if (Rawon.isSelected()) {
            menu = "Nasi Rawon";
            harga = 15000;
            hitung = jumlah * harga;
        }
        else if (bebek.isSelected()) {
            menu = "Bebek Goreng";
            harga = 15000;
            hitung = jumlah * harga;
        }
        else if (Lele.isSelected()) {
            menu = "Pecel Lele";
            harga = 15000;
            hitung = jumlah * harga;
        }
        else if (Ayam.isSelected()) {
            menu = "Ayam Goreng";
            harga = 15000;
            hitung = jumlah * harga;
        }
        else if (Bihun.isSelected()) {
            menu = "Bihun";
            harga = 10000;
            hitung = jumlah * harga;
        }
        else if (Padang.isSelected()) {
            menu = "Nasi Padang";
            harga = 15000;
            hitung = jumlah * harga;
        }
        else if (Lalapan.isSelected()) {
            menu = "Lalapan Tempe Tahu";
            harga = 10000;
            hitung = jumlah * harga;
        }

        isipesanan.setText(""+ menu);
        isihargasatuan.setText(""+ harga);
        isijumlah.setText(""+ jumlah);
        isitotalbayar.setText("" + hitung);
        JOptionPane.showMessageDialog(null, "Pesanan berhasil", "Success!",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_okActionPerformed

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
        // TODO add your handling code here:
        int a = Integer.parseInt(jumlahtransaksi.getText());

        int b = a+1;
        jumlahtransaksi.setText(Integer.toString(b));

        if (a>=100){
            jumlahtransaksi.setText("0");
        }
    }//GEN-LAST:event_plusActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuMakanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Ayam;
    private javax.swing.JRadioButton Bihun;
    private javax.swing.JRadioButton Campur;
    private javax.swing.JRadioButton Lalapan;
    private javax.swing.JRadioButton Lele;
    private javax.swing.JRadioButton Padang;
    private javax.swing.JRadioButton Rawon;
    private javax.swing.JRadioButton Soto;
    private javax.swing.JRadioButton bebek;
    private javax.swing.JButton btnKeluar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel hargasatuan;
    private javax.swing.JLabel hargasatuan1;
    private javax.swing.JLabel head;
    private javax.swing.JTextField isihargasatuan;
    private javax.swing.JTextField isijumlah;
    private javax.swing.JTextField isipesanan;
    private javax.swing.JTextField isitotalbayar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jumlah;
    private javax.swing.JLabel jumlahtransaksi;
    private javax.swing.JButton minus;
    private javax.swing.JButton ok;
    private javax.swing.JButton plus;
    private javax.swing.JLabel totalbayar;
    // End of variables declaration//GEN-END:variables
}